dataSetPath = '../../Dataset/'
captionsPath = dataSetPath + 'annotations/captions_val2014.json'
imagePath = dataSetPath + 'val2014/'
encodedPath = dataSetPath + 'Encoded/' + 'val2014/'
inputsPath = '../my_inputs/'
missionFileName = 'mission.txt'
examplesFileName = 'examples.txt'
taskFileName = 'task.txt'
tempPath = '../temp/'
resultsPath = '../my_results/'
GPT_MODEL = 'gpt-3.5-turbo-instruct'
# GPT_MODEL = 'gpt-4-turbo-preview'
# GPT_MODEL = 'gpt-4-vision-preview'
# GPT_MODEL = 'gpt-4'


